from os import environ

WRIKE_ACCESS_TOKEN = environ["WRIKE_ACCESS_TOKEN"]
TODOIST_ACCESS_TOKEN = environ["TODOIST_ACCESS_TOKEN"]
TODOIST_PROJECT_NAME = environ["TODOIST_PROJECT_NAME"]
TODOIST_LABEL = environ["TODOIST_LABEL"]
